package Clases;
// Generated 20/10/2018 01:21:38 by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private String dni;
     private String apellido;
     private String nombre;
     private String direccion;
     private String telefono;
     private String fechaNacimiento;
     private String EMail;
     private String tutor;
     private String estado;

    public Alumnos() {
    }

	
    public Alumnos(String dni, String apellido, String nombre, String direccion, String telefono, String fechaNacimiento, String EMail) {
        this.dni = dni;
        this.apellido = apellido;
        this.nombre = nombre;
        this.direccion = direccion;
        this.telefono = telefono;
        this.fechaNacimiento = fechaNacimiento;
        this.EMail = EMail;
    }
    public Alumnos(String dni, String apellido, String nombre, String direccion, String telefono, String fechaNacimiento, String EMail, String tutor, String estado) {
       this.dni = dni;
       this.apellido = apellido;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.fechaNacimiento = fechaNacimiento;
       this.EMail = EMail;
       this.tutor = tutor;
       this.estado = estado;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(String fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public String getTutor() {
        return this.tutor;
    }
    
    public void setTutor(String tutor) {
        this.tutor = tutor;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


