package Clases;
// Generated 20/10/2018 01:21:38 by Hibernate Tools 4.3.1



/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private String dni;
     private String apellido;
     private String nombre;
     private String materia;

    public Profesor() {
    }

	
    public Profesor(String dni) {
        this.dni = dni;
    }
    public Profesor(String dni, String apellido, String nombre, String materia) {
       this.dni = dni;
       this.apellido = apellido;
       this.nombre = nombre;
       this.materia = materia;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMateria() {
        return this.materia;
    }
    
    public void setMateria(String materia) {
        this.materia = materia;
    }




}


